[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
    "pip3 install --upgrade pip",
    "pip3 install -r qkd_webapp/requirements.txt"
]

[start]
cmd = "uvicorn qkd_webapp.backend.socketio_app:app --host 0.0.0.0 --port $PORT"
